version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    timezone: PST8PDT
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.19.0
  rebase-strategy: disabled
